.TH yKINE 3 2009-Jul "linux" "heatherly custom tools manual"

.SH NAME
.BI yKINE
\- shared, consistent, and reliable spider kinematics/scripting

.SH SUMMARY
.BI yKINE
is a consistent, shared, full-featured, and reliable spider
kinematics and scripting library designed around the lynxmotion CH3-R hexapod
which will free all other applications from this detailed work.

